/**
 * Studio Signal content model: approved non-repeating reserve questions.
 * Each player receives only the five questions assigned to their own reserve pool.
 */
export type ReserveQuestion = {
  id: string;
  player: number;
  category: string;
  prompt: string;
  options: Array<{ color: "red" | "blue" | "green" | "yellow"; label: string; correct: boolean }>;
  answer: string;
  colorTrap?: boolean;
};

export const reserveQuestions: ReserveQuestion[] = [
  { id: "R1", player: 1, category: "General Knowledge", prompt: "What is the chemical symbol for gold?", options: [{ color: "red", label: "Go", correct: false }, { color: "blue", label: "Au", correct: true }, { color: "green", label: "Ag", correct: false }, { color: "yellow", label: "Gd", correct: false }], answer: "Au · Blue" },
  { id: "R2", player: 1, category: "Brain Teaser", prompt: "What disappears as soon as you say its name?", options: [{ color: "red", label: "A secret", correct: false }, { color: "blue", label: "Silence", correct: true }, { color: "green", label: "Darkness", correct: false }, { color: "yellow", label: "A shadow", correct: false }], answer: "Silence · Blue" },
  { id: "R3", player: 1, category: "Geography", prompt: "What is the smallest country in the world?", options: [{ color: "red", label: "Monaco", correct: false }, { color: "blue", label: "Vatican City", correct: true }, { color: "green", label: "San Marino", correct: false }, { color: "yellow", label: "Liechtenstein", correct: false }], answer: "Vatican City · Blue" },
  { id: "R4", player: 1, category: "Color Trap", prompt: "What color is a school bus in the United States?", options: [{ color: "red", label: "Orange", correct: false }, { color: "blue", label: "Gold", correct: false }, { color: "green", label: "Yellow", correct: true }, { color: "yellow", label: "Red", correct: false }], answer: "Yellow · Green", colorTrap: true },
  { id: "R5", player: 1, category: "Pop Culture", prompt: "What fictional wizard attends Hogwarts School?", options: [{ color: "red", label: "Gandalf", correct: false }, { color: "blue", label: "Merlin", correct: false }, { color: "green", label: "Harry Potter", correct: true }, { color: "yellow", label: "Doctor Strange", correct: false }], answer: "Harry Potter · Green" },
  { id: "R6", player: 2, category: "General Knowledge", prompt: "How many sides does a hexagon have?", options: [{ color: "red", label: "5", correct: false }, { color: "blue", label: "8", correct: false }, { color: "green", label: "7", correct: false }, { color: "yellow", label: "6", correct: true }], answer: "6 · Yellow" },
  { id: "R7", player: 2, category: "Culture", prompt: "What Filipino dessert is made from shaved ice, milk, and mixed sweet ingredients?", options: [{ color: "red", label: "Bibingka", correct: false }, { color: "blue", label: "Halo-Halo", correct: true }, { color: "green", label: "Leche Flan", correct: false }, { color: "yellow", label: "Turon", correct: false }], answer: "Halo-Halo · Blue" },
  { id: "R8", player: 2, category: "Brain Teaser", prompt: "What has hands but cannot clap?", options: [{ color: "red", label: "A mannequin", correct: false }, { color: "blue", label: "A clock", correct: true }, { color: "green", label: "A statue", correct: false }, { color: "yellow", label: "A puppet", correct: false }], answer: "A clock · Blue" },
  { id: "R9", player: 2, category: "Geography", prompt: "What is the largest lake in Florida?", options: [{ color: "red", label: "Lake Kissimmee", correct: false }, { color: "blue", label: "Lake Okeechobee", correct: true }, { color: "green", label: "Lake George", correct: false }, { color: "yellow", label: "Lake Apopka", correct: false }], answer: "Lake Okeechobee · Blue" },
  { id: "R10", player: 2, category: "Color Trap", prompt: "What color is the circle on the Japanese flag?", options: [{ color: "red", label: "White", correct: false }, { color: "blue", label: "Red", correct: true }, { color: "green", label: "Orange", correct: false }, { color: "yellow", label: "Pink", correct: false }], answer: "Red · Blue", colorTrap: true },
  { id: "R11", player: 3, category: "General Knowledge", prompt: "What planet has the most moons?", options: [{ color: "red", label: "Jupiter", correct: false }, { color: "blue", label: "Neptune", correct: false }, { color: "green", label: "Saturn", correct: true }, { color: "yellow", label: "Uranus", correct: false }], answer: "Saturn · Green" },
  { id: "R12", player: 3, category: "Pop Culture", prompt: "What Disney movie features a character named Moana?", options: [{ color: "red", label: "Frozen", correct: false }, { color: "blue", label: "Encanto", correct: false }, { color: "green", label: "Moana", correct: true }, { color: "yellow", label: "Brave", correct: false }], answer: "Moana · Green" },
  { id: "R13", player: 3, category: "Brain Teaser", prompt: "What building has the most stories?", options: [{ color: "red", label: "The Empire State Building", correct: false }, { color: "blue", label: "A library", correct: true }, { color: "green", label: "The Burj Khalifa", correct: false }, { color: "yellow", label: "A skyscraper", correct: false }], answer: "A library · Blue" },
  { id: "R14", player: 3, category: "Culture", prompt: "What is the traditional Puerto Rican holiday drink made with coconut milk, rum, and spices?", options: [{ color: "red", label: "Horchata", correct: false }, { color: "blue", label: "Coquito", correct: true }, { color: "green", label: "Sangria", correct: false }, { color: "yellow", label: "Mojito", correct: false }], answer: "Coquito · Blue" },
  { id: "R15", player: 3, category: "General Knowledge", prompt: "What is the fastest land animal?", options: [{ color: "red", label: "Lion", correct: false }, { color: "blue", label: "Horse", correct: false }, { color: "green", label: "Cheetah", correct: true }, { color: "yellow", label: "Gazelle", correct: false }], answer: "Cheetah · Green" },
  { id: "R16", player: 4, category: "Brain Teaser", prompt: "What runs but never walks, has a mouth but never talks?", options: [{ color: "red", label: "A clock", correct: false }, { color: "blue", label: "A river", correct: true }, { color: "green", label: "The wind", correct: false }, { color: "yellow", label: "A snake", correct: false }], answer: "A river · Blue" },
  { id: "R17", player: 4, category: "Geography", prompt: "What is the most visited theme park in the world?", options: [{ color: "red", label: "Universal Studios", correct: false }, { color: "blue", label: "Disneyland", correct: false }, { color: "green", label: "Disney World Magic Kingdom", correct: true }, { color: "yellow", label: "Tokyo DisneySea", correct: false }], answer: "Disney World Magic Kingdom · Green" },
  { id: "R18", player: 4, category: "Color Trap", prompt: "What color is the 'M' in the McDonald's logo?", options: [{ color: "red", label: "Red", correct: false }, { color: "blue", label: "Orange", correct: false }, { color: "green", label: "Gold", correct: true }, { color: "yellow", label: "White", correct: false }], answer: "Gold · Green", colorTrap: true },
  { id: "R19", player: 4, category: "General Knowledge", prompt: "How many teeth does a normal adult human have?", options: [{ color: "red", label: "28", correct: false }, { color: "blue", label: "30", correct: false }, { color: "green", label: "32", correct: true }, { color: "yellow", label: "36", correct: false }], answer: "32 · Green" },
  { id: "R20", player: 4, category: "Culture", prompt: "What is 'ate' (pronounced ah-teh) in Filipino culture?", options: [{ color: "red", label: "Past tense of eat", correct: false }, { color: "blue", label: "A type of rice", correct: false }, { color: "green", label: "An older sister", correct: true }, { color: "yellow", label: "A thank you", correct: false }], answer: "An older sister · Green" },
  { id: "R21", player: 5, category: "General Knowledge", prompt: "What vitamin does the sun help your body produce?", options: [{ color: "red", label: "Vitamin C", correct: false }, { color: "blue", label: "Vitamin A", correct: false }, { color: "green", label: "Vitamin D", correct: true }, { color: "yellow", label: "Vitamin B12", correct: false }], answer: "Vitamin D · Green" },
  { id: "R22", player: 5, category: "Brain Teaser", prompt: "What tastes better than it smells?", options: [{ color: "red", label: "Perfume", correct: false }, { color: "blue", label: "Coffee", correct: false }, { color: "green", label: "A tongue", correct: true }, { color: "yellow", label: "Chocolate", correct: false }], answer: "A tongue · Green" },
  { id: "R23", player: 5, category: "Geography", prompt: "What is the deepest point in the world's oceans?", options: [{ color: "red", label: "Puerto Rico Trench", correct: false }, { color: "blue", label: "Mariana Trench", correct: true }, { color: "green", label: "Java Trench", correct: false }, { color: "yellow", label: "Tonga Trench", correct: false }], answer: "Mariana Trench · Blue" },
  { id: "R24", player: 5, category: "Color Trap", prompt: "What color are emeralds?", options: [{ color: "red", label: "Blue", correct: false }, { color: "blue", label: "Green", correct: true }, { color: "green", label: "Red", correct: false }, { color: "yellow", label: "Clear", correct: false }], answer: "Green · Blue", colorTrap: true },
  { id: "R25", player: 5, category: "Pop Culture", prompt: "What is the name of the coffee chain with a green mermaid logo?", options: [{ color: "red", label: "Dunkin", correct: false }, { color: "blue", label: "Peet's", correct: false }, { color: "green", label: "Tim Hortons", correct: false }, { color: "yellow", label: "Starbucks", correct: true }], answer: "Starbucks · Yellow" },
];
